AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Lambda
Resources:
  CDLambda0:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: lf0
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lf0
      Description: "Lambda function for CD"
      MemorySize: 128
      Timeout: 30
      Role: ""
      Environment:
        Variables:
          REGION: us-east-1
  CDLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: lf1
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lf1
      Description: "Lambda function for CD"
      MemorySize: 128
      Timeout: 30
      Role: ""
      Environment:
        Variables:
          REGION: us-east-1
  CDLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: lf2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lf2
      Description: "Lambda function for CD"
      MemorySize: 128
      Timeout: 30
      Role: ""
      Environment:
        Variables:
          REGION: us-east-1
